language: node_js
node_js: '10'

git:
  depth: 3

branches:
  only:
    - master
    - /^greenkeeper/.*$/

services: mongodb

env:
  global:
    - NODE_ENV=test
    - PORT=3000
    - MONGO_URI=mongodb://localhost:27017/iam-a-messenger
    - MONGO_URI_TESTS=mongodb://localhost:27017/iam-a-messenger

script: yarn validate

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

# deploy:
# - provider: script
#   script: yarn deploy

after_success: yarn coverage
