version: '3.2'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  # Here is our back end REST web service.
  api-service:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 2112:2112
    environment:
      - MONGO_URI=mongodb://mongodb:27017/iam-a-messenger
      - MONGO_URI_TESTS=mongodb://mongodb:27017/iam-a-messenger
      - NODE_ENV=production
      - DOCKER_FLAG=docker_production
    depends_on:
      - mongodb