FROM node:alpine

MAINTAINER Alex Friedrichsen <afriedrichsen@me.com>

ENV NODE_ENV=production
ENV MONGO_URI=http://mongo/iam-a-messenger
ENV MONGO_URI_TESTS=mongodb://mongo/iam-a-messenger
ENV PORT=2112
ENV DOCKER_FLAG=docker_prod

# Update
RUN apk add --update nodejs

WORKDIR /app


ADD . /app

RUN ls /app

RUN npm install

RUN npm install -g apidoc opn

EXPOSE 2112

RUN npm run prestart

CMD [ "node","app/server/index.js"]