FROM socialengine/nginx-spa:5.6



MAINTAINER Alex Friedrichsen <afriedrichsen@me.com>

ENV NODE_ENV=production
ENV MONGO_URI=http://mongo/iam-a-messenger
ENV MONGO_URI_TESTS=mongodb://mongo/iam-a-messenger
ENV PORT=2112
ENV DOCKER_FLAG=docker_prod

# Update
RUN apk add --update nodejs

WORKDIR /app

ADD build/ /app

RUN cd /app; npm install --production

EXPOSE 2112

CMD [ "npm","start"]