FROM node:alpine

MAINTAINER Alex Friedrichsen <afriedrichsen@me.com>

ENV NODE_ENV=production
ENV MONGO_URI=http://mongo/iam-a-messenger
ENV MONGO_URI_TESTS=mongodb://mongo/iam-a-messenger
ENV PORT=2112
ENV DOCKER_FLAG=docker_prod

# Update
RUN apk add --update nodejs

WORKDIR /app

# Grab front end "build" directory (e.g. yarn build)
ADD app/client/build /app

RUN npm install -g serve

EXPOSE 5000

CMD [ "serve","start"]